# web:
#   image: 'gitlab/gitlab-ce:latest'
#   restart: always
#   hostname: 'gitlab.example.com'
#   environment:
#     GITLAB_OMNIBUS_CONFIG: |
#       external_url 'https://gitlab.example.com'
#       # Add any other gitlab.rb configuration here, each on its own line
#   ports:
#     - '80:80'
#     - '443:443'
#     - '22:22'
#   volumes:
#     - '$GITLAB_HOME/config:/etc/gitlab'
#     - '$GITLAB_HOME/logs:/var/log/gitlab'
#     - '$GITLAB_HOME/data:/var/opt/gitlab'

version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: "gitlab"
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        unicorn['worker_timeout'] = 120
        unicorn['worker_processes'] = 2
    ports:
      - 80:80
      - 443:443
      - 22:22
    networks:
      - front-tier
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
  
  # gitlab-runner:
  #   image: gitlab/gitlab-runner:alpine
  #   container_name: "gitlab-runner"
  #   restart: always
  #   depends_on:
  #     - gitlab
  #   volumes:
  #     - ./config/gitlab-runner:/etc/gitlab-runner
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - front-tier
  
  # artifactory:
  #   image: docker.bintray.io/jfrog/artifactory-pro:latest
  #   container_name: "artifactory"
  #   restart: always
  #   hostname: 'localhost'
  #   ports:
  #     - 8082:8082
  #     - 8081:8081
  #   networks:
  #     - front-tier
  #   volumes:
  #     - ./artifactory:/var/opt/jfrog/artifactory
    

networks:
  front-tier:
    driver: bridge